// shad0w runtime in plain JavaScript, no dependencies. This file is the CommonJS build; index.mjs is the same code
// as an ES module, generated by `node build.mjs` (a test checks they stay in sync).
// Reads a compiled .s0 table and decides in microseconds.
// Works in Node, browsers, Deno, Bun and edge workers. Hashing and arithmetic mirror shad0w/features.py and
// shad0w/_native/reflex.c exactly; the test suite checks that all three runtimes make identical decisions.
"use strict";

const BITS = 22, MASK = (1 << BITS) - 1, MAX_WORD = 256, TABLE_VERSION = 1;
const enc = new TextEncoder();

function fnv(prefix, bytes, start, end) {
  let h = Math.imul(0x811c9dc5 ^ prefix, 0x01000193) >>> 0;
  for (let i = start; i < end; i++) h = Math.imul(h ^ bytes[i], 0x01000193) >>> 0;
  return (h & MASK) >>> 0;
}

/** Words: runs of ASCII letters/digits or any byte >= 0x80, ASCII-lowercased (so every script passes through). */
function words(text) {
  const b = enc.encode(text);
  const out = [];
  let cur = [];
  for (let i = 0; i < b.length; i++) {
    let c = b[i];
    if (c >= 65 && c <= 90) c += 32;
    if ((c >= 48 && c <= 57) || (c >= 97 && c <= 122) || c >= 0x80) {
      if (cur.length < MAX_WORD) cur.push(c);
    } else if (cur.length) { out.push(Uint8Array.from(cur)); cur = []; }
  }
  if (cur.length) out.push(Uint8Array.from(cur));
  return out;
}

/** Hashed items: word unigrams, word bigrams and character trigrams, each FNV-1a hashed to 22 bits. */
function items(text) {
  const ws = words(text);
  const out = [];
  for (const w of ws) {
    out.push(fnv(119 /* 'w' */, w, 0, w.length));
    const p = new Uint8Array(w.length + 2);
    p[0] = 32; p.set(w, 1); p[w.length + 1] = 32;
    for (let i = 0; i + 3 <= p.length; i++) out.push(fnv(99 /* 'c' */, p, i, i + 3));
  }
  for (let i = 0; i + 1 < ws.length; i++) {
    const a = ws[i], c = ws[i + 1];
    const buf = new Uint8Array(a.length + 1 + c.length);
    buf.set(a, 0); buf[a.length] = 1; buf.set(c, a.length + 1);
    out.push(fnv(98 /* 'b' */, buf, 0, buf.length));
  }
  if (!out.length) out.push(fnv(101 /* 'e' */, new Uint8Array(0), 0, 0));
  return out;
}

function toArrayBuffer(x) {
  if (x instanceof ArrayBuffer) return x;
  if (ArrayBuffer.isView(x)) return x.buffer.slice(x.byteOffset, x.byteOffset + x.byteLength);
  throw new TypeError("expected an ArrayBuffer, a typed array or a Node Buffer");
}

/** One compiled question: an int8 table over hashed items. */
class Table {
  constructor(buffer, labels) {
    buffer = toArrayBuffer(buffer);
    if (buffer.byteLength < 20) throw new Error("not a shad0w table (too short)");
    const dv = new DataView(buffer);
    const magic = String.fromCharCode(...new Uint8Array(buffer, 0, 4));
    if (magic !== "S0RX") throw new Error("not a shad0w table");
    const ver = dv.getUint32(4, true), F = dv.getUint32(8, true), K = dv.getUint32(12, true);
    if (ver !== TABLE_VERSION) throw new Error(`table format version ${ver} is not supported`);
    if (K < 2 || K > 1024 || F < 1 || F > (1 << 22)) throw new Error("corrupt table header");
    if (buffer.byteLength !== 20 + 4 * F + F * K + 8 * K + 4 * K * K) throw new Error("truncated or padded table");
    this.temperature = dv.getFloat32(16, true);
    if (!(this.temperature > 0) || !Number.isFinite(this.temperature)) throw new Error("corrupt table header");
    let o = 20;
    this.keys = new Uint32Array(buffer.slice(o, o + 4 * F)); o += 4 * F;
    this.T = new Int8Array(buffer, o, F * K); o += F * K;
    this.scale = new Float32Array(buffer.slice(o, o + 4 * K)); o += 4 * K;
    this.bias = new Float32Array(buffer.slice(o, o + 4 * K));
    this.F = F; this.K = K; this.labels = labels || null;
    this.acc = new Int32Array(K);
  }

  row(h) {
    let lo = 0, hi = this.F - 1;
    while (lo <= hi) {
      const mid = (lo + hi) >>> 1, k = this.keys[mid];
      if (k === h) return mid;
      if (k < h) lo = mid + 1; else hi = mid - 1;
    }
    return -1;
  }

  /** Scores every option. Returns {index, choice, confidence, probabilities}. */
  decide(text) {
    const its = items(String(text)), K = this.K, acc = this.acc;
    acc.fill(0);
    for (const h of its) {
      const r = this.row(h);
      if (r < 0) continue;
      const base = r * K;
      for (let j = 0; j < K; j++) acc[j] += this.T[base + j];
    }
    const n = its.length, z = new Float64Array(K);
    let best = 0, mx = -Infinity;
    for (let j = 0; j < K; j++) {
      z[j] = Math.fround((Math.fround(Math.fround(acc[j] * this.scale[j]) / n) + this.bias[j]) / this.temperature);
      if (z[j] > mx) { mx = z[j]; best = j; }
    }
    let s = 0;
    for (let j = 0; j < K; j++) { z[j] = Math.exp(z[j] - mx); s += z[j]; }
    const probabilities = Array.from(z, (v) => v / s);
    return { index: best, choice: this.labels ? this.labels[best] : best, confidence: probabilities[best], probabilities };
  }
}

/** A compiled bundle: every question's table plus the certified thresholds from manifest.json. */
class Bundle {
  constructor(manifest, tables) {
    this.manifest = manifest;
    this.questions = {};
    for (const [name, q] of Object.entries(manifest.questions)) {
      if (!tables[name]) throw new Error(`missing table for question "${name}"`);
      this.questions[name] = { spec: q, table: new Table(tables[name], q.options) };
    }
  }

  /**
   * Load a bundle directory. In Node pass a path; in browsers and workers pass a URL (or a path relative to the page).
   * @param {string} base  directory or URL that holds manifest.json and <question>.s0
   */
  static async load(base) {
    const b = String(base).replace(/\/+$/, "");
    const remote = /^(https?:|blob:|data:)/.test(b) || typeof process === "undefined" || !process.versions || !process.versions.node;
    if (remote) {
      const get = async (f) => { const r = await fetch(`${b}/${f}`); if (!r.ok) throw new Error(`${f}: HTTP ${r.status}`); return r; };
      const manifest = await (await get("manifest.json")).json();
      const tables = {};
      for (const name of Object.keys(manifest.questions)) tables[name] = await (await get(`${name}.s0`)).arrayBuffer();
      return new Bundle(manifest, tables);
    }
    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    const manifest = JSON.parse(await fs.readFile(path.join(b, "manifest.json"), "utf8"));
    const tables = {};
    for (const name of Object.keys(manifest.questions)) tables[name] = await fs.readFile(path.join(b, `${name}.s0`));
    return new Bundle(manifest, tables);
  }

  /**
   * Decide every question (or only `opts.questions`). Each answer says whether it is certified: serve it if so,
   * otherwise call your model. Same fields as the Python runtime except radius and drift (Python only).
   */
  decide(text, opts = {}) {
    const answers = {};
    for (const [name, { spec, table }] of Object.entries(this.questions)) {
      if (opts.questions && !opts.questions.includes(name)) continue;
      const d = table.decide(text);
      const thr = spec.threshold === null || spec.threshold === undefined ? Infinity : spec.threshold;
      const flag = spec.calibrated === false ? "uncalibrated" : d.confidence < thr ? "low_confidence" : null;
      const out = { confidence: d.confidence, certified: flag === null, flag };
      if (spec.type === "yesno") { out.answer = d.index === 1; out.probability = d.probabilities[1]; }
      else {
        out.choice = d.choice;
        out.probabilities = Object.fromEntries(spec.options.map((o, i) => [o, d.probabilities[i]]));
      }
      answers[name] = out;
    }
    return { answers };
  }
}

module.exports = { Table, Bundle, items, words, TABLE_VERSION };
