// shad0w runtime in plain JavaScript, no dependencies. This file is the CommonJS build; index.mjs is the same code
// as an ES module, generated by `node build.mjs` (a test checks they stay in sync).
// Reads a compiled .s0 table and decides in microseconds; Shadow + openaiTeacher put it in front of any LLM.
// Works in Node, browsers, Deno, Bun and edge workers. Hashing and arithmetic mirror shad0w/features.py and
// shad0w/_native/reflex.c exactly; the test suite checks that all three runtimes make identical decisions.
"use strict";

const BITS = 22, MASK = (1 << BITS) - 1, MAX_WORD = 256, TABLE_VERSION = 1;
const enc = new TextEncoder();

function fnv(prefix, bytes, start, end) {
  let h = Math.imul(0x811c9dc5 ^ prefix, 0x01000193) >>> 0;
  for (let i = start; i < end; i++) h = Math.imul(h ^ bytes[i], 0x01000193) >>> 0;
  return (h & MASK) >>> 0;
}

/** Words: runs of ASCII letters/digits or any byte >= 0x80, ASCII-lowercased (so every script passes through). */
function words(text) {
  const b = enc.encode(text);
  const out = [];
  let cur = [];
  for (let i = 0; i < b.length; i++) {
    let c = b[i];
    if (c >= 65 && c <= 90) c += 32;
    if ((c >= 48 && c <= 57) || (c >= 97 && c <= 122) || c >= 0x80) {
      if (cur.length < MAX_WORD) cur.push(c);
    } else if (cur.length) { out.push(Uint8Array.from(cur)); cur = []; }
  }
  if (cur.length) out.push(Uint8Array.from(cur));
  return out;
}

/** Hashed items: word unigrams, word bigrams and character trigrams, each FNV-1a hashed to 22 bits.
 *  Computed straight from the UTF-8 bytes with no per-word allocation (same hashes as words() + the obvious loops). */
const PRIME = 0x01000193;
/** The C core's slot scramble (murmur3 finaliser). */
function mix(h) {
  h ^= h >>> 16; h = Math.imul(h, 0x7feb352d) >>> 0; h ^= h >>> 15; h = Math.imul(h, 0x846ca68b) >>> 0; h ^= h >>> 16;
  return h >>> 0;
}
function items(text) {
  const b = enc.encode(text), n = b.length;
  const ws = [], we = [];  // word spans [start, end) in b, lowercased in place, truncated to MAX_WORD bytes
  let i = 0;
  while (i < n) {
    let c = b[i];
    if (c >= 65 && c <= 90) c += 32;
    if (!((c >= 48 && c <= 57) || (c >= 97 && c <= 122) || c >= 0x80)) { i++; continue; }
    const st = i;
    while (i < n) {
      let d = b[i];
      if (d >= 65 && d <= 90) { d += 32; b[i] = d; }
      if (!((d >= 48 && d <= 57) || (d >= 97 && d <= 122) || d >= 0x80)) break;
      i++;
    }
    ws.push(st); we.push(Math.min(i, st + MAX_WORD));
  }
  const out = [];
  for (let w = 0; w < ws.length; w++) {
    const st = ws[w], L = we[w] - st;
    let h = Math.imul(0x811c9dc5 ^ 119, PRIME) >>> 0;          // word: 'w' + bytes
    for (let j = st; j < st + L; j++) h = Math.imul(h ^ b[j], PRIME) >>> 0;
    out.push((h & MASK) >>> 0);
    for (let j = 0; j + 3 <= L + 2; j++) {                     // trigrams of " " + word + " ": 'c' + 3 bytes
      let t = Math.imul(0x811c9dc5 ^ 99, PRIME) >>> 0;
      for (let q = j; q < j + 3; q++) t = Math.imul(t ^ (q === 0 || q === L + 1 ? 32 : b[st + q - 1]), PRIME) >>> 0;
      out.push((t & MASK) >>> 0);
    }
  }
  for (let w = 0; w + 1 < ws.length; w++) {                    // bigrams: 'b' + word1 + 0x01 + word2
    let h = Math.imul(0x811c9dc5 ^ 98, PRIME) >>> 0;
    for (let j = ws[w]; j < we[w]; j++) h = Math.imul(h ^ b[j], PRIME) >>> 0;
    h = Math.imul(h ^ 1, PRIME) >>> 0;
    for (let j = ws[w + 1]; j < we[w + 1]; j++) h = Math.imul(h ^ b[j], PRIME) >>> 0;
    out.push((h & MASK) >>> 0);
  }
  if (!out.length) out.push(fnv(101 /* 'e' */, new Uint8Array(0), 0, 0));
  return out;
}

function toArrayBuffer(x) {
  if (x instanceof ArrayBuffer) return x;
  if (ArrayBuffer.isView(x)) return x.buffer.slice(x.byteOffset, x.byteOffset + x.byteLength);
  throw new TypeError("expected an ArrayBuffer, a typed array or a Node Buffer");
}

/** One compiled question: an int8 table over hashed items. */
class Table {
  constructor(buffer, labels) {
    buffer = toArrayBuffer(buffer);
    if (buffer.byteLength < 20) throw new Error("not a shad0w table (too short)");
    const dv = new DataView(buffer);
    const magic = String.fromCharCode(...new Uint8Array(buffer, 0, 4));
    if (magic !== "S0RX") throw new Error("not a shad0w table");
    const ver = dv.getUint32(4, true), F = dv.getUint32(8, true), K = dv.getUint32(12, true);
    if (ver !== TABLE_VERSION) throw new Error(`table format version ${ver} is not supported`);
    if (K < 2 || K > 1024 || F < 1 || F > (1 << 22)) throw new Error("corrupt table header");
    if (buffer.byteLength !== 20 + 4 * F + F * K + 8 * K + 4 * K * K) throw new Error("truncated or padded table");
    this.temperature = dv.getFloat32(16, true);
    if (!(this.temperature > 0) || !Number.isFinite(this.temperature)) throw new Error("corrupt table header");
    let o = 20;
    this.keys = new Uint32Array(buffer.slice(o, o + 4 * F)); o += 4 * F;
    this.T = new Int8Array(buffer, o, F * K); o += F * K;
    this.scale = new Float32Array(buffer.slice(o, o + 4 * K)); o += 4 * K;
    this.bias = new Float32Array(buffer.slice(o, o + 4 * K));
    this.F = F; this.K = K; this.labels = labels || null;
    // open-addressing index key -> row (as the C core does): one or two probes instead of a binary search
    let cap = 1; while (cap < 2 * F) cap <<= 1;
    this.cap = cap; this.slotKey = new Uint32Array(cap); this.slotRow = new Int32Array(cap);
    for (let r = 0; r < F; r++) {
      let i = mix(this.keys[r]) & (cap - 1);
      while (this.slotKey[i] !== 0) i = (i + 1) & (cap - 1);
      this.slotKey[i] = this.keys[r] + 1; this.slotRow[i] = r;
    }
    this.acc = new Int32Array(K);
  }

  row(h) {
    const cap = this.cap - 1, want = h + 1;  // keys are < 2^22, so key + 1 never wraps and 0 marks an empty slot
    let i = mix(h) & cap;
    for (;;) {
      const k = this.slotKey[i];
      if (k === want) return this.slotRow[i];
      if (k === 0) return -1;
      i = (i + 1) & cap;
    }
  }

  /** Scores every option. Returns {index, choice, confidence, probabilities}. */
  /** Scores every option. probabilities=false skips building the per-option array (the fast path). */
  decide(text, probabilities = true) {
    const its = items(String(text)), K = this.K, acc = this.acc;
    acc.fill(0);
    for (const h of its) {
      const r = this.row(h);
      if (r < 0) continue;
      const base = r * K;
      for (let j = 0; j < K; j++) acc[j] += this.T[base + j];
    }
    const n = its.length, z = this.z || (this.z = new Float64Array(K));
    let best = 0, mx = -Infinity;
    for (let j = 0; j < K; j++) {
      z[j] = Math.fround((Math.fround(Math.fround(acc[j] * this.scale[j]) / n) + this.bias[j]) / this.temperature);
      if (z[j] > mx) { mx = z[j]; best = j; }
    }
    let s = 0;
    for (let j = 0; j < K; j++) { z[j] = Math.exp(z[j] - mx); s += z[j]; }
    const choice = this.labels ? this.labels[best] : best;
    if (!probabilities) return { index: best, choice, confidence: z[best] / s, p1: K > 1 ? z[1] / s : 0 };
    const p = Array.from(z, (v) => v / s);
    return { index: best, choice, confidence: p[best], probabilities: p };
  }
}

/** A compiled bundle: every question's table plus the certified thresholds from manifest.json. */
class Bundle {
  constructor(manifest, tables) {
    this.manifest = manifest;
    this.questions = {};
    for (const [name, q] of Object.entries(manifest.questions)) {
      if (!tables[name]) throw new Error(`missing table for question "${name}"`);
      this.questions[name] = { spec: q, table: new Table(tables[name], q.options) };
    }
  }

  /**
   * Load a bundle directory. In Node pass a path; in browsers and workers pass a URL (or a path relative to the page).
   * @param {string} base  directory or URL that holds manifest.json and <question>.s0
   */
  static async load(base) {
    const b = String(base).replace(/\/+$/, "");
    const remote = /^(https?:|blob:|data:)/.test(b) || typeof process === "undefined" || !process.versions || !process.versions.node;
    if (remote) {
      const get = async (f) => { const r = await fetch(`${b}/${f}`); if (!r.ok) throw new Error(`${f}: HTTP ${r.status}`); return r; };
      const manifest = await (await get("manifest.json")).json();
      const tables = {};
      for (const name of Object.keys(manifest.questions)) tables[name] = await (await get(`${name}.s0`)).arrayBuffer();
      return new Bundle(manifest, tables);
    }
    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    const manifest = JSON.parse(await fs.readFile(path.join(b, "manifest.json"), "utf8"));
    const tables = {};
    for (const name of Object.keys(manifest.questions)) tables[name] = await fs.readFile(path.join(b, `${name}.s0`));
    return new Bundle(manifest, tables);
  }

  /**
   * Decide every question (or only `opts.questions`). Each answer says whether it is certified: serve it if so,
   * otherwise call your model. Same fields as the Python runtime except radius and drift (Python only).
   */
  decide(text, opts = {}) {
    const answers = {};
    for (const [name, { spec, table }] of Object.entries(this.questions)) {
      if (opts.questions && !opts.questions.includes(name)) continue;
      const full = opts.probabilities !== false;
      const d = table.decide(text, full);
      const thr = spec.threshold === null || spec.threshold === undefined ? Infinity : spec.threshold;
      const flag = spec.calibrated === false ? "uncalibrated" : d.confidence < thr ? "low_confidence" : null;
      const out = { confidence: d.confidence, certified: flag === null, flag };
      if (spec.type === "yesno") { out.answer = d.index === 1; out.probability = full ? d.probabilities[1] : d.p1; }
      else {
        out.choice = d.choice;
        if (full) out.probabilities = Object.fromEntries(spec.options.map((o, i) => [o, d.probabilities[i]]));
      }
      answers[name] = out;
    }
    return { answers };
  }
}

// ---------------------------------------------------------------------------------------------------------------
// The cascade: the table when it is certified, your LLM otherwise. Mirrors shad0w.Shadow / shad0w.llm_teacher.

/** provider -> [base URL, environment variable holding the key (null for local servers)] */
const PROVIDERS = {
  openai: ["https://api.openai.com/v1", "OPENAI_API_KEY"],
  anthropic: ["https://api.anthropic.com/v1", "ANTHROPIC_API_KEY"],
  gemini: ["https://generativelanguage.googleapis.com/v1beta/openai", "GEMINI_API_KEY"],
  groq: ["https://api.groq.com/openai/v1", "GROQ_API_KEY"],
  together: ["https://api.together.xyz/v1", "TOGETHER_API_KEY"],
  openrouter: ["https://openrouter.ai/api/v1", "OPENROUTER_API_KEY"],
  mistral: ["https://api.mistral.ai/v1", "MISTRAL_API_KEY"],
  deepseek: ["https://api.deepseek.com/v1", "DEEPSEEK_API_KEY"],
  fireworks: ["https://api.fireworks.ai/inference/v1", "FIREWORKS_API_KEY"],
  xai: ["https://api.x.ai/v1", "XAI_API_KEY"],
  ollama: ["http://localhost:11434/v1", null],
  vllm: ["http://localhost:8000/v1", null],
  lmstudio: ["http://localhost:1234/v1", null],
};

const env = (k) => (typeof process !== "undefined" && process.env ? process.env[k] : undefined);
const canon = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
const now = () => (typeof performance !== "undefined" ? performance.now() : Date.now());

/** Map an LLM reply (text, JSON text or parsed JSON) to exactly one option, or null. Same rules as Python. */
function matchOption(reply, options, field) {
  if (typeof reply === "string") {
    let s = reply.trim().replace(/^```(?:json)?\s*|\s*```$/g, "");
    if (/^[{["]/.test(s)) { try { reply = JSON.parse(s); } catch { reply = s; } } else reply = s;
  }
  if (reply && typeof reply === "object" && !Array.isArray(reply)) {
    for (const k of [field, "answer", "label", "choice", "intent", "category", "class"]) {
      if (k && k in reply) return matchOption(reply[k], options);
    }
    const vals = Object.values(reply).filter((v) => typeof v === "string" || typeof v === "boolean");
    return vals.length === 1 ? matchOption(vals[0], options) : null;
  }
  if (Array.isArray(reply)) return reply.length === 1 ? matchOption(reply[0], options) : null;
  if (typeof reply === "boolean") reply = reply ? "yes" : "no";
  if (typeof reply !== "string" || !reply) return null;
  if (options.includes(reply)) return reply;
  const byCanon = new Map(options.map((o) => [canon(o), o]));
  const c = canon(reply);
  if (byCanon.has(c)) return byCanon.get(c);
  if (options.includes("yes") && options.includes("no") && ["true", "false", "y", "n"].includes(c)) return c === "true" || c === "y" ? "yes" : "no";
  let hits = [...byCanon].filter(([k]) => k && new RegExp(`(^|_)${k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(_|$)`).test(c)).map(([, o]) => o);
  hits = hits.filter((h) => !hits.some((g) => g !== h && canon(g).includes(canon(h))));
  return hits.length === 1 ? hits[0] : null;
}

function normalizeOptions(options, question = "decision") {
  if (Array.isArray(options)) return { question, type: "choice", criteria: Object.fromEntries(options.map((o) => [String(o), null])) };
  if (!options || typeof options !== "object") throw new TypeError("options must be a list of names or a {name: description} object");
  let entry = null;
  if ("criteria" in options || options.type === "yesno") entry = options;
  else if (Object.values(options).every((v) => v && typeof v === "object" && ("criteria" in v || v.type === "yesno"))) {
    question = question in options ? question : Object.keys(options)[0];
    entry = options[question];
  } else return { question, type: "choice", criteria: options };
  const type = entry.type || "choice";
  return { question, type, criteria: type === "yesno" ? { yes: null, no: null } : entry.criteria, instructions: entry.instructions };
}

function prompt({ question, type, criteria, instructions }) {
  if (type === "yesno") {
    return `${instructions || `Answer the question '${question}' about the user's message with yes or no.`}\nReply with JSON: {"answer": "yes"} or {"answer": "no"}. Nothing else.`;
  }
  const lines = [instructions || `Classify the user's message (${question}). Pick exactly one option.`, "Options:"];
  for (const [name, desc] of Object.entries(criteria)) lines.push(`- ${name}${desc ? `: ${desc}` : ""}`);
  lines.push('Reply with JSON: {"answer": "<option>"} using one option name exactly as written. Nothing else.');
  return lines.join("\n");
}

/**
 * A teacher backed by any OpenAI-compatible chat endpoint, via fetch (Node 18+, browsers, Workers, Deno, Bun).
 * @returns async (text) => option
 */
function openaiTeacher(opts) {
  const spec = normalizeOptions(opts.options, opts.question);
  const model = opts.model || "openai/gpt-6-luna";
  let [provider, ...rest] = model.includes("/") ? model.split("/") : ["", model];
  let name = rest.join("/");
  if (!(provider in PROVIDERS)) { provider = ""; name = model; }
  const [defUrl, keyEnv] = PROVIDERS[provider] || ["", null];
  const baseURL = String(opts.baseURL || env("SHAD0W_BASE_URL") || defUrl).replace(/\/+$/, "");
  if (!baseURL) throw new Error(`model "${model}": unknown provider; pass baseURL`);
  const apiKey = opts.apiKey !== undefined ? opts.apiKey : keyEnv ? env(keyEnv) : undefined;
  if (keyEnv && !apiKey) throw new Error(`${provider}: set ${keyEnv} or pass apiKey`);
  const doFetch = opts.fetch || globalThis.fetch;
  const options = spec.type === "yesno" ? ["yes", "no"] : Object.keys(spec.criteria);
  const system = opts.system || prompt(spec);
  const retries = opts.retries ?? 2;
  const timeout = opts.timeout ?? 30000;  // ms per request; a timed-out request is retried like a network error
  let structured = opts.structured ?? true;
  const dropped = new Set();
  const responseFormat = { type: "json_schema", json_schema: { name: String(spec.question).replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64) || "decision", strict: true,
    schema: { type: "object", properties: { answer: { type: "string", enum: options } }, required: ["answer"], additionalProperties: false } } };

  async function complete(text) {
    let attempt = 0, last;
    for (let guard = 0; guard < 10; guard++) {
      const body = { model: name, messages: [{ role: "system", content: system }, { role: "user", content: String(text) }],
        temperature: opts.temperature ?? 0, max_tokens: opts.maxTokens ?? 50 };
      for (const k of dropped) delete body[k];
      if (structured) body.response_format = responseFormat;
      const headers = { "content-type": "application/json", ...(opts.headers || {}) };
      if (apiKey) headers.authorization = `Bearer ${apiKey}`;
      let r;
      const ctl = typeof AbortController !== "undefined" ? new AbortController() : null;
      const timer = ctl ? setTimeout(() => ctl.abort(), timeout) : null;
      try { r = await doFetch(`${baseURL}/chat/completions`, { method: "POST", headers, body: JSON.stringify(body), signal: ctl ? ctl.signal : undefined }); }
      catch (e) { last = e && e.name === "AbortError" ? new Error(`timeout after ${timeout} ms`) : e; r = null; }
      finally { if (timer) clearTimeout(timer); }
      if (r && r.ok) {
        const data = await r.json();
        return (data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content) || "";
      }
      if (r) {
        const detail = (await r.text()).slice(0, 500);
        if (r.status === 400 || r.status === 422) {
          const m = detail.toLowerCase();
          const p = ["temperature", "max_tokens"].find((k) => k in body && m.includes(k));
          if (p) { dropped.add(p); continue; }
          if (structured && /response_format|json_schema|structured|schema|not supported|unsupported/.test(m)) { structured = false; continue; }
        }
        last = new Error(`HTTP ${r.status}: ${detail}`);
        if (r.status !== 429 && r.status < 500) break;
      }
      if (attempt >= retries) break;
      await new Promise((res) => setTimeout(res, Math.min(8000, 500 * 2 ** attempt)));
      attempt++;
    }
    throw new Error(`shad0w teacher ${model}: ${last && last.message ? last.message : last}`);
  }

  const teacher = async (text) => {
    const content = await complete(text);
    const opt = matchOption(content, options, "answer");
    if (opt === null) throw new Error(`shad0w teacher ${model} replied ${JSON.stringify(content.slice(0, 200))}, which matches none of ${options.join(", ")}`);
    return spec.type === "yesno" ? opt === "yes" : opt;
  };
  teacher.question = spec.question;
  teacher.options = options;
  teacher.complete = complete;
  teacher.teacherName = model;
  return teacher;
}

/** Why a decision went where it went, in plain words (mirrors shad0w.cascade._FLAG_WORDS). */
const FLAG_WORDS = {
  null: "certified: answered by the table",
  no_bundle: "no trained table yet: asked your model",
  low_confidence: "table not sure enough to stay inside the certified bound: asked your model",
  low_radius: "input could be flipped by a few edits (exposed mode): asked your model",
  drift: "traffic looks different from calibration: asked your model until re-certified",
  uncalibrated: "table has no certificate: asked your model",
  min_confidence: "below your min_confidence floor (stricter than the certificate): asked your model",
  manual_threshold: "served under force_threshold: NOT covered by the certificate",
  canary: "held back by the canary share: asked your model",
  never_serve: "this label is on never_serve: asked your model",
  shadow: "shadow mode: the table's answer was recorded, your model's was returned",
  off: "mode=off: the table was not consulted",
  options_changed: "your options include ones the table never learned: asked your model until you retrain",
  option_removed: "the table picked an option you removed: asked your model",
};
const explainFlag = (flag) => FLAG_WORDS[flag === null || flag === undefined ? "null" : flag] || String(flag || "");

/**
 * The cascade around one question. Certified answers come from the bundle in microseconds; everything else goes to
 * your teacher (an async function), and those answers are passed to `log` so you can train the next bundle.
 * log: a function(row), a writable stream (row written as one JSON line), or, in Node, a file path.
 */
class Shadow {
  constructor(bundle, opts = {}) {
    if (opts.teacher != null && typeof opts.teacher !== "function") throw new TypeError("teacher must be a function: async (text) => answer");
    this.bundle = bundle || null;
    this.teacher = opts.teacher || null;
    this.question = opts.question || (opts.teacher && opts.teacher.question) || (bundle ? Object.keys(bundle.questions)[0] : "decision");
    if (bundle && !(this.question in bundle.questions)) throw new Error(`question "${this.question}" is not in the bundle`);
    this.auditRate = opts.auditRate ?? 0.01;
    this.onDecision = opts.onDecision || null;
    this.random = opts.random || Math.random;
    this.counts = { table: 0, teacher: 0, fallback: 0, audits: 0, auditDisagreements: 0 };
    this._log = opts.log || null;
    // Options can change after training. Added ones: the table never learned them, so (by default) every decision
    // goes to your model until you retrain. Removed ones: answers naming them are never served. rename maps old
    // labels to new ones without retraining. Same rules as the Python package.
    this.fallback = opts.fallback;  // answer when the table defers and there is no teacher (value or (text) => answer)
    this.rename = opts.rename || {};
    this.onNewOption = opts.onNewOption || "defer";
    this.optionsAdded = []; this.optionsRemoved = [];
    if (bundle && opts.options) {
      const spec = bundle.questions[this.question].spec;
      const want = normalizeOptions(opts.options, this.question);
      if (spec.type !== "yesno" && want.type === "choice") {
        const known = new Set(spec.options.map((o) => this.rename[o] || o));
        const wanted = new Set(Object.keys(want.criteria));
        this.optionsAdded = [...wanted].filter((o) => !known.has(o)).sort();
        this.optionsRemoved = [...known].filter((o) => !wanted.has(o)).sort();
      }
    }
  }

  async _write(row) {
    const log = this._log;
    if (!log) return;
    if (typeof log === "function") return log(row);
    if (typeof log.write === "function") return log.write(JSON.stringify(row) + "\n");
    if (typeof log === "string") {
      const fs = await import("node:fs/promises");
      return fs.appendFile(log, JSON.stringify(row) + "\n", "utf8");
    }
  }

  async _ask(text, source, teacher) {
    if (!teacher) throw new Error("this Shadow has no teacher");
    const answer = await teacher(text);
    if (answer !== null && answer !== undefined) {
      await this._write({ text, [this.question]: answer, source, ts: Math.round(Date.now()) / 1000 });
    }
    return answer;
  }

  /** The bundle's raw answer for this question, or null without a bundle. */
  _table(text, probabilities = false) {
    if (!this.bundle) return null;
    let a = this.bundle.decide(text, { questions: [this.question], probabilities }).answers[this.question];
    if ("choice" in a && Object.keys(this.rename).length) {
      const r = (k) => this.rename[k] || k;
      a = { ...a, choice: r(a.choice) };
      if (a.probabilities) a.probabilities = Object.fromEntries(Object.entries(a.probabilities).map(([k, v]) => [r(k), v]));
    }
    if (this.optionsAdded.length && this.onNewOption !== "serve") a = { ...a, certified: false, flag: "options_changed" };
    else if ("choice" in a && this.optionsRemoved.includes(a.choice)) a = { ...a, certified: false, flag: "option_removed" };
    return a;
  }

  /** The option names this question decides among (from the bundle, else from the teacher). */
  options() {
    if (this.bundle) {
      const spec = this.bundle.questions[this.question].spec;
      return spec.type === "yesno" ? ["yes", "no"] : [...spec.options];
    }
    return this.teacher && this.teacher.options ? [...this.teacher.options] : null;
  }

  /** The certified threshold of this question, or null. */
  threshold() {
    if (!this.bundle) return null;
    const t = this.bundle.questions[this.question].spec.threshold;
    return t === undefined ? null : t;
  }

  _done(d, text, t0) {
    d.question = this.question;
    d.threshold = this.threshold();
    d.latencyUs = (now() - t0) * 1000;
    this.counts[d.source]++;
    if (this.onDecision) { try { this.onDecision(d, text); } catch { /* hooks never break a decision */ } }
    return d;
  }

  _audit(text, local, teacher) {
    if (teacher && this.auditRate && this.random() < this.auditRate) {
      this._ask(text, "audit", teacher).then((truth) => {
        this.counts.audits++;
        if (String(truth) !== String(local)) this.counts.auditDisagreements++;
      }).catch(() => {});
    }
  }

  /**
   * The table's decision when it would be served (counted and logged like any table decision), else null.
   * Never calls the teacher, except for the sampled background spot check.
   */
  async peek(text, opts = {}) {
    const t0 = now();
    const a = this._table(text, opts.probabilities !== false);
    if (!a || !a.certified) return null;
    const local = "choice" in a ? a.choice : a.answer;
    const d = { answer: local, source: "table", confidence: a.confidence, certified: true, flag: null,
      probabilities: a.probabilities || null };
    this._audit(text, local, opts.teacher || this.teacher);
    return this._done(d, text, t0);
  }

  /** Log an answer you obtained from your model yourself, and count it as a teacher decision. */
  async record(text, answer) {
    const t0 = now();
    if (answer !== null && answer !== undefined) {
      await this._write({ text, [this.question]: answer, source: "teacher", ts: Math.round(Date.now()) / 1000 });
    }
    const a = this._table(text);
    const d = { answer, source: "teacher", confidence: a ? a.confidence : null, certified: false, flag: a ? a.flag : "no_bundle" };
    return this._done(d, text, t0);
  }

  /** What the table thinks of `text`, without calling your model: answer, confidence vs threshold, reason, top options. */
  explain(text) {
    const a = this._table(text, true);
    if (!a) return { text, answer: null, confidence: null, threshold: null, certified: false, flag: "no_bundle", why: explainFlag("no_bundle"), top: [] };
    const top = a.probabilities ? Object.entries(a.probabilities).sort((x, y) => y[1] - x[1]).slice(0, 3)
      : [["yes", a.probability], ["no", 1 - a.probability]].sort((x, y) => y[1] - x[1]);
    return { text, answer: "choice" in a ? a.choice : a.answer, confidence: a.confidence, threshold: this.threshold(),
      certified: a.certified, flag: a.flag, why: explainFlag(a.flag), top };
  }

  /** @returns {Promise<{answer, source: "table"|"teacher", confidence, certified, flag, latencyUs}>} */
  async decide(text, opts = {}) {
    const t0 = now();
    const teacher = opts.teacher || this.teacher;
    let d;
    const a = this._table(text);
    if ((!a || !a.certified) && !teacher && this.fallback !== undefined) {   // no teacher: the fallback answers, unlogged
      const answer = typeof this.fallback === "function" ? await this.fallback(text) : this.fallback;
      d = { answer, source: "fallback", confidence: a ? a.confidence : null, certified: false, flag: a ? a.flag : "no_bundle" };
      return this._done(d, text, t0);
    }
    if (!a) {
      const answer = await this._ask(text, "teacher", teacher);
      d = { answer, source: "teacher", confidence: null, certified: false, flag: "no_bundle" };
    } else {
      const local = "choice" in a ? a.choice : a.answer;
      if (a.certified) {
        d = { answer: local, source: "table", confidence: a.confidence, certified: true, flag: null };
        this._audit(text, local, teacher);
      } else {
        const answer = await this._ask(text, "teacher", teacher);
        d = { answer, source: "teacher", confidence: a.confidence, certified: false, flag: a.flag };
      }
    }
    return this._done(d, text, t0);
  }

  stats() {
    const c = { ...this.counts }, total = c.table + c.teacher;
    c.offload = total ? c.table / total : 0;
    c.auditDisagreement = c.audits ? c.auditDisagreements / c.audits : null;
    c.optionsAdded = [...this.optionsAdded]; c.optionsRemoved = [...this.optionsRemoved];
    return c;
  }
}

/**
 * One call to a working cascade: decision("intent", {options, llm: "openai/gpt-6-luna", bundle: "intent.bundle"}).
 * `bundle` may be a Bundle, a path/URL (loaded if it exists) or omitted (every call goes to the LLM and is logged).
 */
async function decision(name, opts = {}) {
  if (name && typeof name === "object") { opts = name; name = opts.name || "decision"; }  // decision({options, llm})
  name = name || "decision";
  let bundle = opts.bundle || null;
  if (typeof bundle === "string") {
    // A bundle that does not exist yet is fine (log-only start); a corrupt or unsupported one is an error.
    try { bundle = await Bundle.load(bundle); }
    catch (e) { if (!isMissing(e)) throw e; bundle = null; }
  }
  let teacher = opts.llm;
  if (typeof teacher === "string") {
    if (!opts.options && bundle) opts = { ...opts, options: bundle.questions[name].spec.options };
    if (!opts.options) throw new Error("pass options so the LLM knows what to choose from");
    const provider = teacher.split("/")[0];
    const t = { ...opts, options: opts.options, model: teacher, question: name };
    teacher = provider === "systemone" ? systemoneTeacher({ ...t, model: teacher.slice("systemone/".length) })
      : provider === "openai-decisions" ? decisionsTeacher({ ...t, model: teacher.slice("openai-decisions/".length) })
      : openaiTeacher(t);
  }
  return new Shadow(bundle, { ...opts, teacher, question: name });
}

function isMissing(e) {
  const s = String((e && (e.code || e.message)) || e);
  return /ENOENT|ENOTDIR|HTTP 404/.test(s);
}

// ---------------------------------------------------------------------------------------------------------------
// Decision-model teachers: System One servers (Jev, Kev, Laya, Ollaya, llama.cpp) and the OpenAI Decisions API.

/** POST JSON with a timeout and retries on network errors, 429 and 5xx. Returns the parsed body. */
async function postJSON(url, headers, body, { fetch: doFetch = globalThis.fetch, timeout = 30000, retries = 2 } = {}) {
  let last;
  for (let attempt = 0; ; attempt++) {
    const ctl = typeof AbortController !== "undefined" ? new AbortController() : null;
    const timer = ctl ? setTimeout(() => ctl.abort(), timeout) : null;
    let r = null;
    try { r = await doFetch(url, { method: "POST", headers: { "content-type": "application/json", ...headers }, body: JSON.stringify(body), signal: ctl ? ctl.signal : undefined }); }
    catch (e) { last = e && e.name === "AbortError" ? new Error(`timeout after ${timeout} ms`) : e; }
    finally { if (timer) clearTimeout(timer); }
    if (r && r.ok) return r.json();
    if (r) {
      last = new Error(`HTTP ${r.status}: ${(await r.text()).slice(0, 500)}`);
      if (r.status !== 429 && r.status < 500) throw last;
    }
    if (attempt >= retries) throw last;
    await new Promise((res) => setTimeout(res, Math.min(8000, 500 * 2 ** attempt)));
  }
}

/**
 * A teacher that asks a System One server (TypeSafe wire format: Jev, Kev, Laya, Ollaya, llama.cpp /v1/systemone).
 * systemoneTeacher({ baseURL: "http://localhost:8009", model: "kev-0.8b", question: "intent", options })
 */
function systemoneTeacher(opts) {
  const spec = normalizeOptions(opts.options, opts.question);
  if (!opts.baseURL) throw new Error("systemoneTeacher: pass baseURL (the server that speaks /v1/systemone)");
  const root = String(opts.baseURL).replace(/\/+$/, "").replace(/\/v1$/, "");
  const options = spec.type === "yesno" ? ["yes", "no"] : Object.keys(spec.criteria);
  const q = spec.type === "yesno"
    ? { type: "noul", instructions: spec.instructions || `Is the answer to '${spec.question}' yes for this text?` }
    : { type: "choice", instructions: spec.instructions || `Classify the text (${spec.question}). Pick exactly one option.`,
        criteria: Object.fromEntries(options.map((o) => [o, spec.criteria[o] || o])) };
  const headers = { ...(opts.headers || {}) };
  if (opts.apiKey) headers.authorization = `Bearer ${opts.apiKey}`;
  const teacher = async (text) => {
    const data = await postJSON(`${root}/v1/systemone`, headers, { model: opts.model || "default", state: String(text), questions: { [spec.question]: q } }, opts);
    const a = data && data.answers && data.answers[spec.question];
    if (!a) throw new Error(`systemone server returned no answer for "${spec.question}"`);
    if (spec.type === "yesno") {
      if (typeof a.answer === "boolean") return a.answer;
      if (typeof a.probability === "number") return a.probability >= 0.5;
      const m = matchOption(a.answer ?? a.choice ?? a.noul, ["yes", "no"]);
      if (m === null) throw new Error(`systemone server replied ${JSON.stringify(a).slice(0, 200)}: not a yes/no`);
      return m === "yes";
    }
    const opt = matchOption(a.choice ?? a.value ?? a.answer, options);
    if (opt === null) throw new Error(`systemone server replied ${JSON.stringify(a).slice(0, 200)}, which matches none of ${options.join(", ")}`);
    return opt;
  };
  teacher.question = spec.question; teacher.options = options; teacher.teacherName = `systemone/${opts.model || "default"}`;
  return teacher;
}

/**
 * A teacher that asks the OpenAI Decisions API (POST /v1/decisions, model gpt-6-luna): one choice or predicate question.
 * decisionsTeacher({ model: "gpt-6-luna", question: "intent", options })   // key from OPENAI_API_KEY or apiKey
 */
function decisionsTeacher(opts) {
  const spec = normalizeOptions(opts.options, opts.question);
  const baseURL = String(opts.baseURL || env("SHAD0W_BASE_URL") || "https://api.openai.com/v1").replace(/\/+$/, "");
  const apiKey = opts.apiKey !== undefined ? opts.apiKey : env("OPENAI_API_KEY");
  if (!apiKey && /api\.openai\.com/.test(baseURL)) throw new Error("openai-decisions: set OPENAI_API_KEY or pass apiKey");
  const options = spec.type === "yesno" ? ["yes", "no"] : Object.keys(spec.criteria);
  const question = spec.type === "yesno"
    ? { type: "predicate", name: spec.question, instructions: spec.instructions || `Is the answer to '${spec.question}' yes for this text?` }
    : { type: "choice", name: spec.question, instructions: spec.instructions || `Classify the text (${spec.question}). Pick exactly one option.`,
        choices: options.map((o) => (spec.criteria[o] ? { value: o, description: spec.criteria[o] } : { value: o })) };
  const headers = { ...(opts.headers || {}) };
  if (apiKey) headers.authorization = `Bearer ${apiKey}`;
  const teacher = async (text) => {
    const data = await postJSON(`${baseURL}/decisions`, headers, { model: opts.model || "gpt-6-luna", input: String(text), questions: [question] }, opts);
    const a = data && Array.isArray(data.answers) ? (data.answers.find((x) => x.name === spec.question) || data.answers[0]) : null;
    if (!a) throw new Error(`decisions API returned no answer for "${spec.question}"`);
    if (a.type === "refusal") throw new Error(`decisions API refused "${spec.question}"`);
    if (spec.type === "yesno") {
      if (typeof a.probability === "number") return a.probability >= 0.5;
      const m = matchOption(a.choice ?? a.value, ["yes", "no"]);
      if (m === null) throw new Error(`decisions API replied ${JSON.stringify(a).slice(0, 200)}: not a yes/no`);
      return m === "yes";
    }
    const opt = matchOption(a.choice ?? a.value, options);
    if (opt === null) throw new Error(`decisions API replied ${JSON.stringify(a).slice(0, 200)}, which matches none of ${options.join(", ")}`);
    return opt;
  };
  teacher.question = spec.question; teacher.options = options; teacher.teacherName = `openai-decisions/${opts.model || "gpt-6-luna"}`;
  return teacher;
}

// ---------------------------------------------------------------------------------------------------------------
// Vercel AI SDK: a language-model middleware and a decision model, both backed by a Shadow.

function lastUserText(prompt) {
  for (let i = (prompt || []).length - 1; i >= 0; i--) {
    const m = prompt[i];
    if (!m || m.role !== "user") continue;
    if (typeof m.content === "string") return m.content;
    if (Array.isArray(m.content)) return m.content.filter((p) => p && p.type === "text").map((p) => p.text).join("\n");
  }
  return null;
}

function resultText(r) {
  if (!r) return "";
  if (Array.isArray(r.content)) return r.content.filter((p) => p && p.type === "text").map((p) => p.text).join("");
  return typeof r.text === "string" ? r.text : "";
}

/**
 * Middleware for `wrapLanguageModel({ model, middleware: shad0wMiddleware(intent) })`.
 * Certified answers come from the table without calling the model; the model's own answers are logged for training.
 * specificationVersion must match the installed `ai` major (ai 5 → "v2", ai 6 → "v3", ai 7 → "v4").
 * format(answer) shapes the reply text (default: the bare option; e.g. a => JSON.stringify({ result: a }) for enum output).
 */
function shad0wMiddleware(shadow, opts = {}) {
  const { specificationVersion = "v3", format = String } = opts;
  const options = opts.options || shadow.options();
  return {
    specificationVersion,
    middlewareVersion: specificationVersion,
    wrapGenerate: async ({ doGenerate, params }) => {
      const text = lastUserText(params && params.prompt);
      if (text !== null) {
        const d = await shadow.peek(text);
        if (d) {
          return { content: [{ type: "text", text: format(d.answer) }], finishReason: "stop",
            usage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 }, warnings: [],
            providerMetadata: { shad0w: { source: "table", answer: d.answer, confidence: d.confidence, certified: true, latencyUs: d.latencyUs } } };
        }
      }
      const r = await doGenerate();
      if (text !== null && options) {
        const a = matchOption(resultText(r), options);
        if (a !== null) await shadow.record(text, shadow.bundle && shadow.bundle.questions[shadow.question].spec.type === "yesno" ? a === "yes" : a);
      }
      return r;
    },
  };
}

/**
 * A decision model for `experimental_decide({ model: decisionModel(intent), state, questions })` (AI SDK, spec v4).
 * `shadows` is one Shadow or { [questionName]: Shadow }. Choice and boolean questions that a Shadow certifies are
 * answered from its table with probabilities; everything else goes to `fallback` (another decision model, e.g.
 * openai.decisionModel("gpt-6-luna")) and the fallback's answers are logged into the matching Shadow for training.
 */
function decisionModel(shadows, opts = {}) {
  const map = shadows instanceof Shadow ? { [shadows.question]: shadows } : { ...shadows };
  const fallback = opts.fallback || null;
  return {
    specificationVersion: "v4",
    provider: opts.provider || "shad0w",
    modelId: opts.name || `shad0w:${Object.keys(map).join("+")}`,
    supportedQuestionTypes: fallback && fallback.supportedQuestionTypes ? [...fallback.supportedQuestionTypes] : ["choice", "boolean"],
    async doDecide({ state, questions, abortSignal, headers, providerOptions }) {
      const text = typeof state === "string" ? state : JSON.stringify(state);
      const answers = {}, pending = {}, meta = { table: [], fallback: [] };
      for (const [id, q] of Object.entries(questions || {})) {
        const sh = map[id];
        const d = sh && (q.type === "choice" || q.type === "boolean") ? await sh.peek(text) : null;
        if (!d) { pending[id] = q; continue; }
        meta.table.push(id);
        if (q.type === "boolean") {
          const p = typeof d.answer === "boolean" ? (d.answer ? d.confidence : 1 - d.confidence) : (d.probabilities ? d.probabilities.yes ?? d.confidence : d.confidence);
          answers[id] = { type: "boolean", probability: p };
        } else {
          const probabilities = d.probabilities ? Object.fromEntries(Object.keys(q.criteria || {}).filter((k) => k in d.probabilities).map((k) => [k, d.probabilities[k]])) : undefined;
          answers[id] = { type: "choice", choice: d.answer, ...(probabilities ? { probabilities } : {}) };
        }
      }
      let usage = { inputTokens: 0, outputTokens: 0 }, warnings = [], response, providerMetadata = {};
      if (Object.keys(pending).length) {
        if (!fallback) {
          for (const id of Object.keys(pending)) { answers[id] = { type: "refusal" }; warnings.push({ type: "other", message: `shad0w: no certified answer for "${id}" and no fallback model` }); }
        } else {
          const r = await fallback.doDecide({ state, questions: pending, abortSignal, headers, providerOptions });
          for (const [id, a] of Object.entries(r.answers || {})) {
            answers[id] = a; meta.fallback.push(id);
            const sh = map[id];
            if (!sh || !a || a.type === "refusal") continue;
            if (a.type === "choice") await sh.record(text, a.choice);
            else if (a.type === "boolean" && typeof a.probability === "number") await sh.record(text, a.probability >= 0.5);
          }
          usage = r.usage || usage; warnings = r.warnings || warnings; response = r.response; providerMetadata = r.providerMetadata || {};
        }
      }
      return { answers, usage, warnings, response, providerMetadata: { ...providerMetadata, shad0w: meta } };
    },
  };
}

module.exports = { Table, Bundle, Shadow, openaiTeacher, systemoneTeacher, decisionsTeacher, decision, shad0wMiddleware, decisionModel,
  explainFlag, FLAG_WORDS, matchOption, PROVIDERS, items, words, TABLE_VERSION };
